TRAINING_TRIALS: ["9"]
EXPERIMENT_TRIALS: ["9"]

# feedback
TRAINING_FEEDBACK: True
EXPERIMENT_FEEDBACK: False
FEEDBACK_SHOW_TIME: 2
FEEDBACK_SIZE: 50
FEEDBACK_POS: [0, 400]


# time in secunds
STIM_TIME: 10
WAIT_TIME: 1

# visual parameters
BACKGROUND_COLOR: Gainsboro
TEXT_SIZE: 32
TASK_SIZE: 400
TASK_POS: [0, 200] # [x, y]
ANSWERS_SIZE: 150
ANSWERS_POS: [0, -200]
VIZ_OFFSET: [30, 30]
N_ANSWERS_IN_ROW: 5

# accept box
ACCEPT_BOX_POS: [500, -300]
ACCEPT_BOX_SIZE: [100, 50]
ACCEPT_BOX_TEXT: Dalej
ACCEPT_BOX_TEXT_FEEDBACK: Sprawd≈∫
START_BOX_COLOR: grey
START_TEXT_COLOR: Gainsboro
END_BOX_COLOR: white
END_TEXT_COLOR: black

# clock
## show clock n second before trial end
SHOW_CLOCK: -1
CLOCK_POS: [0, 0]
CLOCK_SIZE: 50

